import cv2

# OpenCV Settings
BLUE   = (255, 0, 0)
GREEN  = (0, 255, 0)
RED    = (0, 0, 255)
YELLOW = (0,255,255)

BBOX_THICKNESS     = 2
BBOX_CIRCLE_RADIUS = 3
LINE_THICKNESS     = 3

TEXT_FONT = cv2.FONT_HERSHEY_SIMPLEX
TEXT_FONT_SCALE = 1
TEXT_THICKNESS  = 2
TEXT_POS = (50, 50) 

# YOLO Settings
SHOW_YOLO_SCREEN = False
YOLO_THRESHOLD   = 0.2

# Algorithm Settings
COLLUSION_THRESHOLD  = 5
MOUSE_DIFF_THRESHOLD = 10